### ISSUE TITLE
Error in merging rdf files

### ISSUE THREAD

**Issue by matteoLorenzini** [gtadigital/Xml_RDF_mapping#24]
**Describe the bug**
Concatenating multiple .rdf files some entities are grouped into the first record.
**To Reproduce**

```
 <crm:P2_has_type>
      <crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_descr_holding_de/ao_descr_holding_de">
        <crm:P3_has_note xml:lang="en">Devis, Korrespondenz, Notizen</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Pläne (Ingenieur: Ansicht, Schnitte, Grundrisse 1:200; Architekt: Situationsplan, Ansicht 1:500), Berechnungen, Notizen, Offerte, Korrespondenz</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">1 Blatt mit Kontaktabzügen (Fotos sw: Landschaft, Aussen, Baustelle, Betonierung)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Notizen, Skizzen, Sitzungsprotokoll, Briefe, Pflichtenheft, Situationsplan 1:500</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Briefe, Notizen</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Pläne (Ingenieur: Grundrisse, Schnitte und Ansichten 1:200, Schnitte 1:100, Perspektiven), Baubeschrieb und Offerte, Akten</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Korrespondenz, Notizen, diverse Skizzen von Varianten, Berechnungen, Offerten</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">1 Blatt mit Kontaktabzügen (Fotos sw: Aussen, Modell, Baustelle, Pläne)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Pläne (Architekt und Ingenieur: Perspektiven / Publikationspläne, Schalen), Eisenlisten, Fotos sw (Baustelle, Aussen, Innen, Porträt), 2 Modellfotos sw, Messungen, Akten (Notizen, Korrespondenz, Offerte, Berechnungen, Rechnungen)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Pläne (Architekt: Situation 1:1250, Situation 1:500), Artikel</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Auszug (Kopie)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">1 Blatt mit Kontaktabzügen (Fotos sw: Dokumentation Seminar, Modelle)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Skizzen (Bleistift, Aquarell, Kugelschreiber auf lose Karten, Handzettel und in Skizzenbücher); Format A6 bis A3</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">1 Blatt mit Kontaktabzügen (Fotos sw: Landschaft, Aussen, Dach)</crm:P3_has_note>

<crm:E78_Collection rdf:about="https://resource.swissartresearch.net/archivalobject/21740">



</crm:E78_Collection>
```
**Expected behavior**
Only the relative entity to a specific record should be grouped 

```
<crm:E78_Collection rdf:about="https://resource.swissartresearch.net/archivalobject/21740">

        <crm:P3_has_note xml:lang="en">Pläne (Architekt und Ingenieur: Perspektiven / Publikationspläne, Schalen), Eisenlisten, Fotos sw (Baustelle, Aussen, Innen, Porträt), 2 Modellfotos sw, Messungen, Akten (Notizen, Korrespondenz, Offerte, Berechnungen, Rechnungen)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Pläne (Architekt: Situation 1:1250, Situation 1:500), Artikel</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Auszug (Kopie)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">1 Blatt mit Kontaktabzügen (Fotos sw: Dokumentation Seminar, Modelle)</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">Skizzen (Bleistift, Aquarell, Kugelschreiber auf lose Karten, Handzettel und in Skizzenbücher); Format A6 bis A3</crm:P3_has_note>
        <crm:P3_has_note xml:lang="en">1 Blatt mit Kontaktabzügen (Fotos sw: Landschaft, Aussen, Dach)</crm:P3_has_note>

</crm:E78_Collection>


<crm:E78_Collection rdf:about="https://resource.swissartresearch.net/archivalobject/21741">

   <crm:P3_has_note xml:lang="en">Notizen, Skizzen, Sitzungsprotokoll, Briefe, Pflichtenheft, Situationsplan 1:500</crm:P3_has_note>

</crm:E78_Collection>

```

**Comment by ZCRNK** [comment]
As far as I have seen, this bug is fixed in the updated version of xml_to_rdf_mapper.py. 
I did not have time to check the whole output file yet though. I will do it next Friday

**Comment by matteoLorenzini** [comment]
Nope, not fixed.

Moreover: While concatenating multiple files the main entity E78_Collection is ignored.

```
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
  xmlns:crm="http://www.cidoc-crm.org/cidoc-crm/"
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:frbr="http://www.cidoc-crm.org/frbr/"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>
  <crm:E74_Group rdf:about="https://resource.swissartresearch.net/group/d420994b-8052-417a-8ef5-d10734b14575">

...

</rdf:RDF>

**Comment by ZCRNK** [comment]
With the version of the code I uploaded last week and also with the one I uploaded today, I cannot reproduce the error anymore. The nodes to which to which the <crm:P3_has_note...> tags were wrongly appended were:
<crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_ao_descr_notes_de/ao_ao_descr_notes_de"> <crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_descr_holding_de/ao_descr_holding_de"> <crm:E55_Type rdf:about="https://resource.swissartresearch.net/scholar_description_de/scholar_description_de"> <crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_descr_chrono_display_de/ao_descr_chrono_display_de"> <crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_descr_place_display_de/ao_descr_place_display_de"> <crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_descr_actor_display_legacy/ao_descr_actor_display_legacy"> <crm:E55_Type rdf:about="https://resource.swissartresearch.net/ao_descr_archivierung/ao_descr_archivierung">

I checked the instances of these files in the newly generated concatenated output file and the only node appended to them seems to be the <rdfs:label...> tag.

Also, I cannot see that the entity E78_Collection is ignored... 

But maybe I misinterpret something...

Can you maybe send me your output file and the number of the lines to which you refer?
